server:
  port: 8081

spring:
  application:
    name: users-read-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "${USERS_READ_DATASOURCE_URL:jdbc:postgresql://localhost:5433/usersdb}"
    username: "${USERS_READ_DATASOURCE_USER:postgres}"
    password: "${USERS_READ_DATASOURCE_PWD:postgres}"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect